services:
  - type: web
    name: PolyRhythm_Wellness_Bot
    env: docker
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
